sonar.projectKey=mekniamal_SAGE
sonar.organization=mekniamal
sonar.projectName=Amora Laravel Chatbot
sonar.sources=app,routes,database
sonar.tests=tests
sonar.php.coverage.reportPaths=reports/coverage.xml
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**
sonar.php.version=8.1